### PR TITLE
update REx URL, use multipart/form-data request

### LINKED ISSUE #108: Can not generate parsers
### Problem:

The command `grunt parsers` is not working as expected

### Expected behavior:

Generates `JSONiqParser.js` and `XQueryParser.js`

### Actual behavior:

Both `JSONiqParser.js` and `XQueryParser.js` have the same content:

```
Usage: REx [OPTION]... [input-file]

  -ll NUM        use strong-LL(K) algorithm up to K=NUM (default 3)
  -backtrack     allow PEG-style backtracking for LL-conflicts

  -cpp           generate parser in C++
  -csharp        generate parser in C#
  -haxe          generate parser in Haxe
  -java          generate parser in Java
  -javascript    generate parser in JavaScript
  -scala         generate parser in Scala
  -typescript    generate parser in TypeScript
  -xquery        generate parser in XQuery
  -xslt          generate parser in XSLT

  -saxon         generate Saxon 10 extension function (requires -java, too)
  -basex         generate BaseX extension function (requires -java, too)

  -xml           create XML representation of grammar
  -asi           handle EcmaScript automatic semicolon insertion (LL(1) only)
  -name NAME     use non-default class name, or XQuery/XSLT module namespace

  -tree          generate code for parse tree or parsing event handler
  -trace         generate code for tokenizer trace
  -main          generate simple main program
  -performance   generate performance test program
  -faster        optimize speed
  -smaller       optimize memory consumption

  -version       show REx version
```

At first, I was getting a different content, but then I changed:
https://github.com/wcandillon/xqlint/blob/10e3885793fe1cd0c8db1c971777549261732184/Gruntfile.js#L23
to 
```javascript
var r = request.post('https://www.bottlecaps.de/rex/', function(err, res, body) {
```

Also, I set `NODE_TLS_REJECT_UNAUTHORIZED=0` because the certificate is apparently expired

### PR DESCRIPTION
**Pull request by GuntherRademacher**
Make sure that multipart/form-data is integrated into request invocation.

fixes #108

### CODE REVIEW

**Comment by wcandillon** [comment]
Long time no talk @GuntherRademacher 🥲 That brings back a lot of memories.

**Comment by wcandillon** [comment]
@ccheraa does this fixes your issue? if yes I can publish the fix for it

**Comment by ccheraa** [comment]
@wcandillon Yes, I have just tested it and it works as intended.

**Comment by wcandillon** [comment]
`0.5.2` has been published, Thank you @GuntherRademacher for looking into this :)

**Comment by GuntherRademacher** [comment]
> `0.5.2` has been published, Thank you @GuntherRademacher for looking into this :)

It was my pleasure!

**Pull request merged**
