### PR TITLE
Add Processor option

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by joewiz** [comment]
@wcandillon Very nice! To extend xqlint with support for additional processors, we would add to https://github.com/wcandillon/xqlint/blob/d812dbc16b6c9b8ce92762b0e50c870c52da4cf1/lib/compiler/static_context.js#L429-L459, right?

**Comment by wcandillon** [comment]
@joewiz correct :)

**Comment by joewiz** [comment]
@wcandillon Very nice. Would you invite processors like eXist-db to be submitted via PR?

**Comment by joewiz** [comment]
(Or would you prefer people to add this in their own forks/builds? As you wish...)

**Comment by wcandillon** [comment]
@joewiz feel free to submit existdb specific code (same goes for the parser).

**Comment by joewiz** [comment]
@wcandillon Cool, thanks :-)

**Pull request merged**
